name: start_page
description: App to start your day with.

publish_to: 'none' 

version: 0.9.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # utils
  sqflite: ^1.3.2+2
  provider: ^4.3.3
  device_apps: ^1.2.0
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.12+4

  # Widgets
  fluttertoast: ^7.1.6
  flutter_speed_dial: ^1.2.5
  vibration: ^1.7.3

  # parsers
  metadata_fetch: ^0.3.4
  http: ^0.12.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "file-assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:

  uses-material-design: true


  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf